// node scripts/build-map.mjs
// Writes src/data/sri-lanka-map.ts: Sri Lanka's outline as an SVG path (Natural
// Earth 1:10m, via world-atlas) and the Mercator projection that places branch
// pins on it. Run again only to change the map's size or detail.
import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";

import { geoMercator, geoPath } from "d3-geo";
import { feature } from "topojson-client";

const require = createRequire(import.meta.url);
const WIDTH = 400;
const HEIGHT = 640;
const PADDING = 12;

const topology = JSON.parse(
  readFileSync(require.resolve("world-atlas/countries-10m.json"), "utf8"),
);
const countries = feature(topology, topology.objects.countries);
const sriLanka = countries.features.find((f) => f.properties.name === "Sri Lanka");
if (!sriLanka) throw new Error("Sri Lanka not found in world-atlas");

const projection = geoMercator().fitExtent(
  [
    [PADDING, PADDING],
    [WIDTH - PADDING, HEIGHT - PADDING],
  ],
  sriLanka,
);
const path = geoPath(projection).digits(1)(sriLanka);
const [tx, ty] = projection.translate();

writeFileSync(
  "src/data/sri-lanka-map.ts",
  `// Generated by scripts/build-map.mjs from Natural Earth (public domain). Don't edit by hand.

export const SRI_LANKA_VIEWBOX = { width: ${WIDTH}, height: ${HEIGHT} } as const;

/** The island's outline, Mercator, fitted to the view box. */
export const SRI_LANKA_PATH =
  "${path}";

const SCALE = ${projection.scale()};
const TX = ${tx};
const TY = ${ty};

/** Places a latitude/longitude on the map (same Mercator projection as the outline). */
export function projectToMap(lat: number, lng: number): { x: number; y: number } {
  const lambda = (lng * Math.PI) / 180;
  const phi = (lat * Math.PI) / 180;
  return {
    x: TX + SCALE * lambda,
    y: TY - SCALE * Math.log(Math.tan(Math.PI / 4 + phi / 2)),
  };
}
`,
);
console.log(`path ${path.length} chars`);
