/**
 * Generates supabase/seed.sql from src/data/seed.ts.
 *
 *   npm run db:seed
 *
 * Runs on plain Node (type stripping), so it imports with a .ts extension.
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

import * as seed from "../src/data/seed.ts";

type Value = string | number | boolean | null | object | string[];

function literal(value: Value, column: string): string {
  if (value === null) return "null";
  if (typeof value === "boolean") return value ? "true" : "false";
  if (typeof value === "number") {
    if (!Number.isFinite(value)) throw new Error(`Non-finite number in ${column}`);
    return String(value);
  }
  if (typeof value === "string") return quote(value);
  if (Array.isArray(value) && column === "dietary_tags") {
    return value.length === 0 ? "'{}'::text[]" : `array[${value.map(quote).join(", ")}]::text[]`;
  }
  return `${quote(JSON.stringify(value))}::jsonb`;
}

function quote(text: string): string {
  return `'${text.replaceAll("'", "''")}'`;
}

function insert(table: string, rows: readonly object[], conflict: string): string {
  if (rows.length === 0) return "";
  const columns = Object.keys(rows[0]!);
  const values = rows.map((row) => {
    const record = row as Record<string, Value>;
    return `  (${columns.map((column) => literal(record[column] ?? null, column)).join(", ")})`;
  });
  return [
    `insert into public.${table} (${columns.join(", ")}) values`,
    values.join(",\n"),
    `on conflict ${conflict} do nothing;`,
    "",
  ].join("\n");
}

const sql = [
  "-- Generated by scripts/build-seed-sql.ts from src/data/seed.ts. Do not edit by hand.",
  "-- Demo data for Kithul & Co., a fictional restaurant.",
  "",
  insert("branches", seed.branches, "(id)"),
  insert("categories", seed.categories, "(id)"),
  insert("menu_items", seed.menuItems, "(id)"),
  insert("item_options", seed.itemOptions, "(id)"),
  insert("item_option_values", seed.itemOptionValues, "(id)"),
  insert("branch_menu_overrides", seed.branchMenuOverrides, "(branch_id, menu_item_id)"),
  insert("promotions", seed.promotions, "(id)"),
  insert("holidays", seed.holidays, "(id)"),
  insert("reviews", seed.reviews, "(id)"),
  insert("promo_codes", seed.promoCodes, "(id)"),
].join("\n");

const target = fileURLToPath(new URL("../supabase/seed.sql", import.meta.url));
writeFileSync(target, sql);
console.log(
  `Wrote ${target}: ${seed.branches.length} branches, ${seed.categories.length} categories, ` +
    `${seed.menuItems.length} menu items, ${seed.itemOptions.length} option groups, ` +
    `${seed.itemOptionValues.length} option values, ${seed.promotions.length} promotions, ` +
    `${seed.holidays.length} holidays, ${seed.reviews.length} reviews, ${seed.promoCodes.length} promo codes.`,
);
