// Generated by scripts/build-hero-video.mjs. Don't edit by hand.

/** The home hero's video: AV1 first, H.264 for browsers without it. */
export const heroVideo = {
  landscape: {
    width: 1920,
    height: 1080,
    poster: "/media/hero/hero-landscape.91cff04050.jpg",
    sources: [
      {
        src: "/media/hero/hero-landscape.2ccf284eff.av1.mp4",
        type: 'video/mp4; codecs="av01.0.08M.08"',
      },
      {
        src: "/media/hero/hero-landscape.b640036499.h264.mp4",
        type: 'video/mp4; codecs="avc1.640029"',
      },
    ],
  },
  portrait: {
    width: 720,
    height: 1280,
    poster: "/media/hero/hero-portrait.02741e7470.jpg",
    sources: [
      {
        src: "/media/hero/hero-portrait.485bf9ae5d.av1.mp4",
        type: 'video/mp4; codecs="av01.0.05M.08"',
      },
      {
        src: "/media/hero/hero-portrait.e5c4cc802e.h264.mp4",
        type: 'video/mp4; codecs="avc1.640029"',
      },
    ],
  },
};
