/**
 * Demo content for Kithul & Co., a fictional restaurant.
 *
 * Single source of truth for:
 *   - `supabase/seed.sql`, generated by `npm run db:seed` (scripts/build-seed-sql.ts)
 *   - the app's no-database fallback (docs/DECISIONS.md D9), so the site works
 *     before Supabase is configured
 *
 * Rows use the database column names. IDs are derived from slugs so they are
 * identical in every environment.
 *
 * This file must stay runnable by plain Node (type stripping): no path aliases,
 * no enums, and no imports other than `node:` built-ins.
 *
 * Sinhala and Tamil names are drafts and need review by a native speaker.
 */
import { createHash } from "node:crypto";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

export type I18nText = { en: string; si?: string; ta?: string };

/** A UUID derived from a kind and key, so seeds are reproducible. */
export function stableId(kind: string, key: string): string {
  const hex = createHash("sha256").update(`kithul-demo:${kind}:${key}`).digest("hex");
  const variant = ((parseInt(hex[16] ?? "0", 16) & 0x3) | 0x8).toString(16);
  return [
    hex.slice(0, 8),
    hex.slice(8, 12),
    `8${hex.slice(13, 16)}`,
    `${variant}${hex.slice(17, 20)}`,
    hex.slice(20, 32),
  ].join("-");
}

/** Remote photos (credits in docs/CREDITS.md). Served through next/image. */
const unsplash = (id: string) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1600&q=80`;
const pexels = (id: string) =>
  `https://images.pexels.com/photos/${id}/pexels-photo-${id}.jpeg?auto=compress&cs=tinysrgb&w=1600`;

/** Rupees to cents. */
const rs = (rupees: number) => Math.round(rupees * 100);

const t = (en: string, si?: string, ta?: string): I18nText => ({
  en,
  ...(si ? { si } : {}),
  ...(ta ? { ta } : {}),
});

// ---------------------------------------------------------------------------
// Row types (database column names)
// ---------------------------------------------------------------------------

export type DayKey = "mon" | "tue" | "wed" | "thu" | "fri" | "sat" | "sun";
export type OpeningHours = Record<DayKey, [string, string][]>;

export type DeliveryFeeRules = {
  baseFeeCents: number;
  includedKm: number;
  perKmCents: number;
  freeAboveCents: number | null;
};

export type BranchRow = {
  id: string;
  slug: string;
  name_i18n: I18nText;
  address_line: string;
  city: string;
  district: string;
  lat: number;
  lng: number;
  phone: string;
  whatsapp: string | null;
  email: string | null;
  delivery_radius_km: number;
  delivery_fee_rules: DeliveryFeeRules;
  opening_hours: OpeningHours;
  seating_capacity: number;
  image_path: string | null;
  is_accepting_orders: boolean;
  is_active: boolean;
  sort_order: number;
};

export type CategoryRow = {
  id: string;
  slug: string;
  name_i18n: I18nText;
  description_i18n: Partial<I18nText>;
  sort_order: number;
  is_active: boolean;
};

export type DietaryTag = "vegetarian" | "vegan" | "halal" | "contains-nuts";

export type MenuItemRow = {
  id: string;
  category_id: string;
  slug: string;
  name_i18n: I18nText;
  description_i18n: Partial<I18nText>;
  base_price_cents: number;
  image_path: string | null;
  dietary_tags: DietaryTag[];
  spice_selectable: boolean;
  is_alcohol: boolean;
  is_signature: boolean;
  is_active: boolean;
  sort_order: number;
};

export type ItemOptionRow = {
  id: string;
  menu_item_id: string;
  name_i18n: I18nText;
  selection: "single" | "multiple";
  is_required: boolean;
  max_select: number | null;
  sort_order: number;
};

export type ItemOptionValueRow = {
  id: string;
  option_id: string;
  name_i18n: I18nText;
  price_delta_cents: number;
  is_default: boolean;
  is_active: boolean;
  sort_order: number;
};

export type BranchMenuOverrideRow = {
  branch_id: string;
  menu_item_id: string;
  price_cents: number | null;
  is_available: boolean;
};

export type PromotionRow = {
  id: string;
  slug: string;
  title_i18n: I18nText;
  body_i18n: Partial<I18nText>;
  image_path: string | null;
  cta_label_i18n: I18nText | null;
  cta_href: string | null;
  starts_on: string | null;
  ends_on: string | null;
  is_active: boolean;
  sort_order: number;
};

export type HolidayRow = {
  id: string;
  date: string;
  kind: "poya" | "public" | "festival";
  name_i18n: I18nText;
  is_alcohol_free: boolean;
};

export type ReviewRow = {
  id: string;
  branch_id: string | null;
  author_name: string;
  rating: number;
  body: string;
  status: "pending" | "approved" | "rejected";
  created_at: string;
};

// ---------------------------------------------------------------------------
// Branches
// ---------------------------------------------------------------------------

const everyDay = (open: string, close: string): OpeningHours => ({
  mon: [[open, close]],
  tue: [[open, close]],
  wed: [[open, close]],
  thu: [[open, close]],
  fri: [[open, close]],
  sat: [[open, close]],
  sun: [[open, close]],
});

const branch = (row: Omit<BranchRow, "id" | "image_path" | "is_active" | "is_accepting_orders">) =>
  ({
    id: stableId("branch", row.slug),
    image_path: null,
    is_active: true,
    is_accepting_orders: true,
    ...row,
  }) satisfies BranchRow;

// Phone numbers use 000 blocks so they are unlikely to belong to anyone. The
// UI also disables call links in demo mode.
export const branches: BranchRow[] = [
  branch({
    slug: "colombo-07",
    name_i18n: t("Colombo 07", "කොළඹ 07", "கொழும்பு 07"),
    address_line: "42 Flower Road",
    city: "Colombo 07",
    district: "Colombo",
    lat: 6.9112,
    lng: 79.8556,
    phone: "+94110000700",
    whatsapp: "+94770000700",
    email: "colombo07@kithul.example",
    delivery_radius_km: 6,
    delivery_fee_rules: {
      baseFeeCents: rs(250),
      includedKm: 3,
      perKmCents: rs(60),
      freeAboveCents: rs(7500),
    },
    opening_hours: {
      ...everyDay("11:00", "22:30"),
      fri: [["11:00", "23:30"]],
      sat: [["11:00", "23:30"]],
    },
    seating_capacity: 60,
    sort_order: 1,
  }),
  branch({
    slug: "nugegoda",
    name_i18n: t("Nugegoda", "නුගේගොඩ", "நுகேகொடை"),
    address_line: "118 High Level Road",
    city: "Nugegoda",
    district: "Colombo",
    lat: 6.8721,
    lng: 79.889,
    phone: "+94110000800",
    whatsapp: "+94770000800",
    email: "nugegoda@kithul.example",
    delivery_radius_km: 5,
    delivery_fee_rules: {
      baseFeeCents: rs(200),
      includedKm: 3,
      perKmCents: rs(50),
      freeAboveCents: rs(6500),
    },
    opening_hours: everyDay("10:30", "22:00"),
    seating_capacity: 45,
    sort_order: 2,
  }),
  branch({
    slug: "kandy",
    name_i18n: t("Kandy", "මහනුවර", "கண்டி"),
    address_line: "7 Dalada Veediya",
    city: "Kandy",
    district: "Kandy",
    lat: 7.2936,
    lng: 80.6408,
    phone: "+94810000900",
    whatsapp: "+94770000900",
    email: "kandy@kithul.example",
    delivery_radius_km: 4,
    delivery_fee_rules: {
      baseFeeCents: rs(250),
      includedKm: 2,
      perKmCents: rs(70),
      freeAboveCents: rs(7500),
    },
    opening_hours: everyDay("11:00", "22:00"),
    seating_capacity: 50,
    sort_order: 3,
  }),
];

const branchId = (slug: string) => stableId("branch", slug);

// ---------------------------------------------------------------------------
// Categories
// ---------------------------------------------------------------------------

const category = (slug: string, sort: number, name: I18nText, description: string) =>
  ({
    id: stableId("category", slug),
    slug,
    name_i18n: name,
    description_i18n: { en: description },
    sort_order: sort,
    is_active: true,
  }) satisfies CategoryRow;

export const categories: CategoryRow[] = [
  category(
    "rice-and-curry",
    1,
    t("Rice & Curry", "බත් සහ කරි", "சோறும் கறியும்"),
    "Red or white rice with a main curry and the sides a Sri Lankan lunch packet would be proud of.",
  ),
  category(
    "kottu",
    2,
    t("Kottu", "කොත්තු", "கொத்து"),
    "Godamba roti chopped on a hot griddle. Listen for the clatter.",
  ),
  category(
    "hoppers",
    3,
    t("Hoppers & String Hoppers", "ආප්ප සහ ඉඳිආප්ප", "அப்பம் மற்றும் இடியப்பம்"),
    "Made to order from fermented rice flour and fresh coconut milk.",
  ),
  category(
    "devilled",
    4,
    t("Devilled & Grills", "ඩෙවල් සහ ග්‍රිල්", "டெவில் மற்றும் கிரில்"),
    "Sweet, sour and fiery, wok-tossed with onion and capsicum.",
  ),
  category(
    "fried-rice",
    5,
    t("Fried Rice & Noodles", "ෆ්‍රයිඩ් රයිස් සහ නූඩ්ල්ස්", "ஃபிரைட் ரைஸ் மற்றும் நூடுல்ஸ்"),
    "Wok-fried and served with chilli paste, the way the island likes it.",
  ),
  category(
    "seafood",
    6,
    t("From the Sea", "මුහුදු ආහාර", "கடல் உணவு"),
    "Fish, crab and prawns from the morning market.",
  ),
  category(
    "short-eats",
    7,
    t("Short Eats", "කෙටි කෑම", "சிற்றுண்டிகள்"),
    "The tea-time snacks every bakery in Sri Lanka is judged by.",
  ),
  category(
    "desserts",
    8,
    t("Desserts", "අතුරුපස", "இனிப்புகள்"),
    "Kithul treacle, coconut and cardamom.",
  ),
  category("drinks", 9, t("Drinks", "බීම", "பானங்கள்"), "From king coconut to Ceylon tea."),
];

const categoryId = (slug: string) => stableId("category", slug);

// ---------------------------------------------------------------------------
// Option templates
// ---------------------------------------------------------------------------

type OptionTemplate = {
  key: string;
  name: I18nText;
  selection: "single" | "multiple";
  required: boolean;
  maxSelect?: number;
  values: { key: string; name: I18nText; delta: number; isDefault?: boolean }[];
};

const portion = (largeDelta: number): OptionTemplate => ({
  key: "portion",
  name: t("Portion", "ප්‍රමාණය", "அளவு"),
  selection: "single",
  required: true,
  values: [
    { key: "regular", name: t("Regular", "සාමාන්‍ය", "சாதாரண"), delta: 0, isDefault: true },
    { key: "large", name: t("Large", "විශාල", "பெரியது"), delta: rs(largeDelta) },
  ],
});

const addOns = (values: OptionTemplate["values"], maxSelect?: number): OptionTemplate => ({
  key: "add-ons",
  name: t("Add-ons", "අමතර", "கூடுதல்"),
  selection: "multiple",
  required: false,
  maxSelect,
  values,
});

const ADD = {
  papadam: {
    key: "papadam",
    name: t("Extra papadam", "අමතර පපඩම්", "கூடுதல் அப்பளம்"),
    delta: rs(100),
  },
  friedEgg: {
    key: "fried-egg",
    name: t("Fried egg", "බිත්තර බැදුම", "பொரித்த முட்டை"),
    delta: rs(150),
  },
  curryOfTheDay: {
    key: "curry-of-the-day",
    name: t("Extra curry of the day", "අමතර කරියක්", "கூடுதல் கறி"),
    delta: rs(350),
  },
  seeniSambol: {
    key: "seeni-sambol",
    name: t("Seeni sambol", "සීනි සම්බෝල", "சீனி சம்பல்"),
    delta: rs(150),
  },
  cheese: {
    key: "extra-cheese",
    name: t("Extra cheese", "අමතර චීස්", "கூடுதல் சீஸ்"),
    delta: rs(350),
  },
  chicken: {
    key: "extra-chicken",
    name: t("Extra chicken", "අමතර චිකන්", "கூடுதல் சிக்கன்"),
    delta: rs(450),
  },
  gravy: { key: "extra-gravy", name: t("Extra gravy", "අමතර හොදි", "கூடுதல் குழம்பு"), delta: 0 },
  raita: { key: "raita", name: t("Extra raita", "අමතර රයිටා", "கூடுதல் ரைத்தா"), delta: rs(150) },
  boiledEgg: {
    key: "boiled-egg",
    name: t("Boiled egg", "තැම්බූ බිත්තරය", "அவித்த முட்டை"),
    delta: rs(120),
  },
  chickenCurry: {
    key: "chicken-curry",
    name: t("Chicken curry", "චිකන් කරිය", "கோழிக் கறி"),
    delta: rs(450),
  },
  dhal: { key: "dhal-curry", name: t("Dhal curry", "පරිප්පු", "பருப்புக் கறி"), delta: rs(250) },
  rice: { key: "steamed-rice", name: t("Steamed rice", "බත්", "சோறு"), delta: rs(300) },
  chips: { key: "chips", name: t("Chips", "චිප්ස්", "சிப்ஸ்"), delta: rs(350) },
  devilledSide: {
    key: "devilled-chicken-side",
    name: t("Devilled chicken on the side", "ඩෙවල් චිකන්", "டெவில் சிக்கன்"),
    delta: rs(650),
  },
  iceCream: {
    key: "ice-cream",
    name: t("Scoop of vanilla ice cream", "අයිස්ක්‍රීම්", "ஐஸ்கிரீம்"),
    delta: rs(200),
  },
} as const;

const serveWith: OptionTemplate = {
  key: "serve-with",
  name: t("Serve with", "සමඟ", "உடன்"),
  selection: "single",
  required: true,
  values: [
    { key: "rice", name: t("Steamed rice", "බත්", "சோறு"), delta: 0, isDefault: true },
    {
      key: "roti",
      name: t("Godamba roti (2)", "ගෝදම්බා රොටී (2)", "கோதம்பா ரொட்டி (2)"),
      delta: rs(100),
    },
    {
      key: "string-hoppers",
      name: t("String hoppers (10)", "ඉඳිආප්ප (10)", "இடியப்பம் (10)"),
      delta: rs(200),
    },
  ],
};

const OPTIONS = {
  riceAndCurry: [
    portion(350),
    addOns([ADD.papadam, ADD.friedEgg, ADD.curryOfTheDay, ADD.seeniSambol]),
  ],
  biriyani: [portion(500), addOns([ADD.raita, ADD.boiledEgg])],
  kottu: [portion(450), addOns([ADD.cheese, ADD.friedEgg, ADD.chicken, ADD.gravy])],
  meatlessKottu: [portion(450), addOns([ADD.cheese, ADD.friedEgg, ADD.gravy])],
  veganKottu: [portion(400), addOns([ADD.gravy])],
  hoppers: [addOns([ADD.seeniSambol, ADD.chickenCurry, ADD.dhal])],
  hopperFeast: [
    {
      key: "curry",
      name: t("Curry", "කරිය", "கறி"),
      selection: "single",
      required: true,
      values: [
        {
          key: "chicken",
          name: t("Chicken curry", "චිකන් කරිය", "கோழிக் கறி"),
          delta: 0,
          isDefault: true,
        },
        { key: "fish", name: t("Fish curry", "මාළු කරිය", "மீன் கறி"), delta: rs(150) },
        {
          key: "vegetable",
          name: t("Vegetable curry", "එළවළු කරිය", "காய்கறிக் கறி"),
          delta: rs(-300),
        },
      ],
    },
  ],
  devilled: [portion(600), addOns([ADD.rice, ADD.chips])],
  friedRice: [portion(450), addOns([ADD.friedEgg, ADD.devilledSide])],
  seafood: [serveWith],
  dessert: [addOns([ADD.iceCream])],
  tea: [
    {
      key: "style",
      name: t("Style", "ආකාරය", "வகை"),
      selection: "single",
      required: true,
      values: [
        { key: "plain", name: t("Plain", "කහට", "சாதாரண"), delta: 0, isDefault: true },
        { key: "milk", name: t("With milk", "කිරි තේ", "பால் தேநீர்"), delta: rs(50) },
        { key: "ginger", name: t("With ginger", "ඉඟුරු තේ", "இஞ்சி தேநீர்"), delta: rs(50) },
      ],
    },
  ],
  lime: [
    {
      key: "style",
      name: t("Style", "ආකාරය", "வகை"),
      selection: "single",
      required: true,
      values: [
        { key: "sweet", name: t("Sweet", "පැණි රස", "இனிப்பு"), delta: 0, isDefault: true },
        { key: "salted", name: t("Salted", "ලුණු රස", "உப்பு"), delta: 0 },
      ],
    },
  ],
} satisfies Record<string, OptionTemplate[]>;

// ---------------------------------------------------------------------------
// Menu items
// ---------------------------------------------------------------------------

type ItemSpec = {
  slug: string;
  name: I18nText;
  description: string;
  price: number;
  tags?: DietaryTag[];
  spicy?: boolean;
  alcohol?: boolean;
  signature?: boolean;
  options?: OptionTemplate[];
  image?: string;
};

const MENU: Record<string, ItemSpec[]> = {
  "rice-and-curry": [
    {
      slug: "chicken-rice-and-curry",
      image: unsplash("photo-1708658767771-718c38b75a9b"),
      name: t("Chicken rice & curry", "චිකන් බත් සහ කරි", "கோழி சோறும் கறியும்"),
      description:
        "Red or white rice with a slow-cooked chicken curry, dhal, two vegetable curries, pol sambol and papadam.",
      price: 1450,
      tags: ["halal"],
      spicy: true,
      signature: true,
      options: OPTIONS.riceAndCurry,
    },
    {
      slug: "fish-rice-and-curry",
      image: unsplash("photo-1665332398215-825114bbb355"),
      name: t("Fish rice & curry", "මාළු බත් සහ කරි", "மீன் சோறும் கறியும்"),
      description:
        "Seer fish curry soured with goraka, with dhal, two vegetable curries, pol sambol and papadam.",
      price: 1550,
      tags: ["halal"],
      spicy: true,
      options: OPTIONS.riceAndCurry,
    },
    {
      slug: "vegetable-rice-and-curry",
      image: unsplash("photo-1743674453123-93356ade2891"),
      name: t("Vegetable rice & curry", "එළවළු බත් සහ කරි", "காய்கறி சோறும் கறியும்"),
      description:
        "Five vegetable curries of the day with dhal, gotukola mallung, pol sambol and papadam.",
      price: 1150,
      tags: ["vegan"],
      spicy: true,
      options: OPTIONS.riceAndCurry,
    },
    {
      slug: "black-pork-curry",
      name: t(
        "Black pork curry & rice",
        "කළු ඌරු මස් කරිය සහ බත්",
        "கறுப்பு பன்றிக் கறியும் சோறும்",
      ),
      description:
        "Pork belly slow-cooked with dark-roasted curry powder and goraka, with rice, dhal and seeni sambol.",
      price: 1850,
      spicy: true,
      options: OPTIONS.riceAndCurry,
    },
    {
      slug: "lamprais",
      name: t("Lamprais", "ලම්ප්‍රයිස්", "லம்பிரைஸ்"),
      description:
        "The Dutch Burgher classic: rice cooked in stock, mixed meat curry, frikkadels, blachan, seeni sambol and ash plantain, baked in a banana leaf.",
      price: 2250,
      signature: true,
    },
    {
      slug: "chicken-biriyani",
      image: unsplash("photo-1631515243349-e0cb75fb8d3a"),
      name: t("Chicken biriyani", "චිකන් බුරියානි", "சிக்கன் பிரியாணி"),
      description:
        "Fragrant basmati layered with spiced chicken, with raita, mint sambol and a boiled egg. Topped with fried cashews.",
      price: 1950,
      tags: ["halal", "contains-nuts"],
      spicy: true,
      options: OPTIONS.biriyani,
    },
    {
      slug: "mutton-biriyani",
      image: unsplash("photo-1589302168068-964664d93dc0"),
      name: t("Mutton biriyani", "එළු මස් බුරියානි", "ஆட்டிறைச்சி பிரியாணி"),
      description:
        "Mutton on the bone, slow-cooked into saffron basmati, with raita, mint sambol and fried cashews.",
      price: 2450,
      tags: ["halal", "contains-nuts"],
      spicy: true,
      options: OPTIONS.biriyani,
    },
  ],
  kottu: [
    {
      slug: "chicken-kottu",
      image: pexels("35071814"),
      name: t("Chicken kottu", "චිකන් කොත්තු", "சிக்கன் கொத்து"),
      description:
        "Godamba roti chopped on the griddle with chicken curry, leeks, carrot and egg. Comes with extra gravy.",
      price: 1650,
      tags: ["halal"],
      spicy: true,
      signature: true,
      options: OPTIONS.kottu,
    },
    {
      slug: "cheese-chicken-kottu",
      name: t("Cheese chicken kottu", "චීස් චිකන් කොත්තු", "சீஸ் சிக்கன் கொத்து"),
      description: "Our chicken kottu, finished with a generous melt of cheese.",
      price: 1950,
      tags: ["halal"],
      spicy: true,
      options: OPTIONS.kottu,
    },
    {
      slug: "dolphin-kottu",
      name: t("Dolphin kottu", "ඩොල්ෆින් කොත්තු", "டால்பின் கொத்து"),
      description:
        "Long ribbons of roti tossed with chicken curry and a rich cheese sauce. Named for the shape of the roti, not what's in it.",
      price: 2150,
      tags: ["halal"],
      spicy: true,
      signature: true,
      options: OPTIONS.kottu,
    },
    {
      slug: "egg-kottu",
      name: t("Egg kottu", "බිත්තර කොත්තු", "முட்டை கொத்து"),
      description: "Godamba roti chopped with three eggs, vegetables and curry gravy.",
      price: 1250,
      tags: ["vegetarian"],
      spicy: true,
      options: OPTIONS.meatlessKottu,
    },
    {
      slug: "vegetable-kottu",
      name: t("Vegetable kottu", "එළවළු කොත්තු", "காய்கறி கொத்து"),
      description:
        "Roti chopped with leeks, cabbage, carrot and a vegetable curry. Made without egg.",
      price: 1150,
      tags: ["vegan"],
      spicy: true,
      options: OPTIONS.veganKottu,
    },
    {
      slug: "mutton-kottu",
      image: pexels("34772939"),
      name: t("Mutton kottu", "එළු මස් කොත්තු", "ஆட்டிறைச்சி கொத்து"),
      description: "Chopped roti with tender mutton curry, red onion and green chilli.",
      price: 2250,
      tags: ["halal"],
      spicy: true,
      options: OPTIONS.meatlessKottu,
    },
    {
      slug: "string-hopper-kottu",
      name: t("String hopper kottu", "ඉඳිආප්ප කොත්තු", "இடியப்ப கொத்து"),
      description:
        "Steamed string hoppers chopped with chicken, egg and vegetables. Lighter than roti kottu.",
      price: 1550,
      tags: ["halal"],
      spicy: true,
      options: OPTIONS.kottu,
    },
  ],
  hoppers: [
    {
      slug: "plain-hoppers",
      image: pexels("39851684"),
      name: t("Plain hoppers (2)", "ආප්ප (2)", "அப்பம் (2)"),
      description:
        "Bowl-shaped rice flour and coconut milk pancakes, crisp at the edge and soft in the middle. With lunu miris.",
      price: 380,
      tags: ["vegan"],
      options: OPTIONS.hoppers,
    },
    {
      slug: "egg-hoppers",
      image: pexels("40003887"),
      name: t("Egg hoppers (2)", "බිත්තර ආප්ප (2)", "முட்டை அப்பம் (2)"),
      description: "Hoppers with an egg cooked into the centre. With lunu miris.",
      price: 620,
      tags: ["vegetarian"],
      signature: true,
      options: OPTIONS.hoppers,
    },
    {
      slug: "milk-hoppers",
      name: t("Milk hoppers (2)", "කිරි ආප්ප (2)", "பால் அப்பம் (2)"),
      description: "Sweet hoppers with a pool of set coconut milk in the middle.",
      price: 480,
      tags: ["vegan"],
    },
    {
      slug: "string-hoppers",
      image: pexels("14132109"),
      name: t("String hoppers (10)", "ඉඳිආප්ප (10)", "இடியப்பம் (10)"),
      description: "Ten steamed rice-flour nests with kiri hodi, pol sambol and dhal curry.",
      price: 750,
      tags: ["vegan"],
      options: OPTIONS.hoppers,
    },
    {
      slug: "pittu",
      image: pexels("17104944"),
      name: t("Pittu", "පිට්ටු", "பிட்டு"),
      description:
        "Steamed cylinders of rice flour and grated coconut, with coconut milk and a vegetable curry.",
      price: 850,
      tags: ["vegan"],
    },
    {
      slug: "hopper-feast",
      image: pexels("37179402"),
      name: t("Hopper feast for two", "දෙදෙනෙකුට ආප්ප", "இருவருக்கான அப்ப விருந்து"),
      description:
        "Four plain and two egg hoppers with a curry, dhal, seeni sambol and lunu miris.",
      price: 2650,
      options: OPTIONS.hopperFeast,
    },
  ],
  devilled: [
    {
      slug: "devilled-chicken",
      image: unsplash("photo-1766567461692-32c352d198d4"),
      name: t("Devilled chicken", "ඩෙවල් චිකන්", "டெவில் சிக்கன்"),
      description:
        "Crisp-fried chicken tossed in a sweet, sour and fiery sauce with onion, capsicum and tomato.",
      price: 1850,
      tags: ["halal"],
      spicy: true,
      signature: true,
      options: OPTIONS.devilled,
    },
    {
      slug: "devilled-prawns",
      name: t("Devilled prawns", "ඩෙවල් ඉස්සෝ", "டெவில் இறால்"),
      description: "Juicy prawns wok-tossed with chilli, onion and capsicum.",
      price: 2650,
      tags: ["halal"],
      spicy: true,
      options: OPTIONS.devilled,
    },
    {
      slug: "hot-butter-cuttlefish",
      name: t("Hot butter cuttlefish", "හොට් බටර් දැල්ලෝ", "ஹாட் பட்டர் கணவாய்"),
      description:
        "Crisp battered cuttlefish tossed in butter, garlic, chilli flakes and spring onion.",
      price: 2350,
      tags: ["halal"],
      spicy: true,
      options: OPTIONS.devilled,
    },
    {
      slug: "devilled-sausages",
      name: t("Devilled chicken sausages", "ඩෙවල් සොසේජස්", "டெவில் சாசேஜ்"),
      description: "A Sri Lankan bar classic: chicken sausages in a sticky devilled sauce.",
      price: 1450,
      tags: ["halal"],
      spicy: true,
      options: OPTIONS.devilled,
    },
    {
      slug: "devilled-potatoes",
      image: unsplash("photo-1646398123647-695431536f7c"),
      name: t("Devilled potatoes", "ඩෙවල් අර්තාපල්", "டெவில் உருளைக்கிழங்கு"),
      description: "Crushed baby potatoes fried until crisp, then tossed in chilli and onion.",
      price: 750,
      tags: ["vegan"],
      spicy: true,
    },
  ],
  "fried-rice": [
    {
      slug: "chicken-fried-rice",
      image: unsplash("photo-1603133872878-684f208fb84b"),
      name: t("Chicken fried rice", "චිකන් ෆ්‍රයිඩ් රයිස්", "சிக்கன் ஃபிரைட் ரைஸ்"),
      description:
        "Wok-fried basmati with chicken, egg, leeks and carrot, with chilli paste and a fried drumstick.",
      price: 1650,
      tags: ["halal"],
      spicy: true,
      options: OPTIONS.friedRice,
    },
    {
      slug: "mixed-fried-rice",
      image: unsplash("photo-1512058564366-18510be2db19"),
      name: t("Mixed fried rice", "මික්ස් ෆ්‍රයිඩ් රයිස්", "கலவை ஃபிரைட் ரைஸ்"),
      description:
        "Chicken, prawns, cuttlefish and egg, with chilli paste and devilled chicken on the side.",
      price: 2250,
      tags: ["halal"],
      spicy: true,
      options: OPTIONS.friedRice,
    },
    {
      slug: "nasi-goreng",
      image: pexels("35783779"),
      name: t("Nasi goreng", "නාසි ගොරේන්", "நாசி கோரெங்"),
      description:
        "Sri Lankan Malay-style fried rice with chicken satay, a fried egg on top and prawn crackers.",
      price: 1950,
      tags: ["halal", "contains-nuts"],
      spicy: true,
      options: OPTIONS.friedRice,
    },
    {
      slug: "vegetable-fried-rice",
      name: t("Vegetable fried rice", "එළවළු ෆ්‍රයිඩ් රයිස්", "காய்கறி ஃபிரைட் ரைஸ்"),
      description: "Basmati wok-fried with seasonal vegetables and soy, made without egg.",
      price: 1250,
      tags: ["vegan"],
      spicy: true,
      options: [portion(400)],
    },
    {
      slug: "chicken-noodles",
      image: unsplash("photo-1692815153957-fefd061f078d"),
      name: t("Chicken noodles", "චිකන් නූඩ්ල්ස්", "சிக்கன் நூடுல்ஸ்"),
      description: "Egg noodles stir-fried with chicken, vegetables and a dash of chilli.",
      price: 1550,
      tags: ["halal"],
      spicy: true,
      options: OPTIONS.friedRice,
    },
  ],
  seafood: [
    {
      slug: "jaffna-crab-curry",
      image: unsplash("photo-1587209310286-b61cdacd694c"),
      name: t("Jaffna crab curry", "යාපනය කකුළු කරිය", "யாழ்ப்பாண நண்டுக் கறி"),
      description:
        "Lagoon crab in a deep, peppery Jaffna curry with murunga leaves. Messy and worth it.",
      price: 3850,
      tags: ["halal"],
      spicy: true,
      signature: true,
      options: OPTIONS.seafood,
    },
    {
      slug: "ambul-thiyal",
      image: unsplash("photo-1620894580123-466ad3a0ca06"),
      name: t("Ambul thiyal", "ඇඹුල් තියල්", "அம்புல் தியல்"),
      description:
        "The southern sour fish curry: tuna cooked down with goraka and black pepper until almost dry.",
      price: 1750,
      tags: ["halal"],
      spicy: true,
      options: OPTIONS.seafood,
    },
    {
      slug: "prawn-curry",
      image: unsplash("photo-1781332143666-5d02f0fe7865"),
      name: t("Prawn curry", "ඉස්සෝ කරිය", "இறால் கறி"),
      description: "Prawns simmered in coconut milk with curry leaves and pandan.",
      price: 2450,
      tags: ["halal"],
      spicy: true,
      options: OPTIONS.seafood,
    },
    {
      slug: "garlic-butter-seer-fish",
      name: t("Garlic butter seer fish", "ගාලික් බටර් තෝරා මාළු", "பூண்டு வெண்ணெய் வஞ்சிர மீன்"),
      description: "Pan-seared seer fish with garlic butter, sautéed vegetables and chips.",
      price: 2650,
      tags: ["halal"],
    },
  ],
  "short-eats": [
    {
      slug: "fish-bun",
      image: pexels("37051967"),
      name: t("Fish bun", "මාළු පාන්", "மீன் பன்"),
      description: "A soft triangle bun filled with spiced fish and potato.",
      price: 180,
    },
    {
      slug: "chicken-roll",
      image: pexels("37051940"),
      name: t("Chicken roll", "චිකන් රෝල්", "சிக்கன் ரோல்"),
      description: "A crumbed and fried pancake roll stuffed with chicken curry and potato.",
      price: 220,
      tags: ["halal"],
    },
    {
      slug: "vegetable-roti",
      name: t("Vegetable roti", "එළවළු රොටී", "காய்கறி ரொட்டி"),
      description: "A triangle of pan-fried roti filled with spiced potato, carrot and leeks.",
      price: 160,
      tags: ["vegan"],
    },
    {
      slug: "fish-cutlets",
      name: t("Fish cutlets (4)", "මාළු කට්ලට් (4)", "மீன் கட்லட் (4)"),
      description: "Crumbed balls of spiced fish, potato and green chilli, with chilli sauce.",
      price: 380,
      tags: ["halal"],
    },
    {
      slug: "isso-wade",
      name: t("Isso wade (2)", "ඉස්සෝ වඩේ (2)", "இறால் வடை (2)"),
      description: "Crunchy lentil fritters topped with whole prawns. A Galle Face Green classic.",
      price: 450,
      tags: ["halal"],
    },
    {
      slug: "ulundu-vadai",
      image: unsplash("photo-1730191843435-073792ba22bc"),
      name: t("Ulundu vadai (2)", "උඳු වඩේ (2)", "உளுந்து வடை (2)"),
      description: "Fluffy urad dal doughnuts with coconut chutney.",
      price: 320,
      tags: ["vegan"],
    },
    {
      slug: "chicken-patties",
      name: t("Chicken patties (3)", "චිකන් පැටිස් (3)", "சிக்கன் பேட்டிஸ் (3)"),
      description: "Flaky half-moon pastries filled with chicken, potato and spices.",
      price: 390,
      tags: ["halal"],
    },
  ],
  desserts: [
    {
      slug: "wattalappan",
      name: t("Wattalappan", "වටලප්පන්", "வட்டலப்பம்"),
      description:
        "Steamed kithul jaggery and coconut custard, spiced with cardamom and nutmeg, topped with cashews.",
      price: 550,
      tags: ["vegetarian", "contains-nuts"],
      signature: true,
      options: OPTIONS.dessert,
    },
    {
      slug: "curd-and-treacle",
      name: t(
        "Buffalo curd & kithul treacle",
        "මී කිරි සහ කිතුල් පැණි",
        "எருமைத் தயிரும் கித்துள் பாணியும்",
      ),
      description: "Set buffalo curd from the south with a pour of pure kithul treacle.",
      price: 650,
      tags: ["vegetarian"],
      signature: true,
    },
    {
      slug: "faluda",
      image: unsplash("photo-1630823186728-b17c9f82a32d"),
      name: t("Faluda", "ෆලූඩා", "பலூடா"),
      description: "Rose syrup, milk, basil seeds and jelly, topped with vanilla ice cream.",
      price: 750,
      tags: ["vegetarian"],
    },
    {
      slug: "caramel-pudding",
      image: unsplash("photo-1752245055475-8b7c3b4756ac"),
      name: t("Caramel pudding", "කැරමල් පුඩිං", "கேரமல் புட்டிங்"),
      description: "Silky baked custard in a dark caramel.",
      price: 450,
      tags: ["vegetarian"],
      options: OPTIONS.dessert,
    },
    {
      slug: "love-cake",
      name: t("Love cake", "ලව් කේක්", "லவ் கேக்"),
      description:
        "Semolina, cashew and pumpkin preserve cake with rose water and spice. A Christmas tradition we serve all year.",
      price: 480,
      tags: ["vegetarian", "contains-nuts"],
      options: OPTIONS.dessert,
    },
  ],
  drinks: [
    {
      slug: "king-coconut",
      image: unsplash("photo-1743947063884-6a69a9b86896"),
      name: t("King coconut", "තැඹිලි", "செவ்விளநீர்"),
      description: "Chilled and served in the shell.",
      price: 350,
      tags: ["vegan"],
    },
    {
      slug: "ceylon-tea",
      image: unsplash("photo-1709926701984-f5ae0099595f"),
      name: t("Ceylon tea", "ලංකා තේ", "இலங்கை தேநீர்"),
      description: "High-grown Dimbula black tea. Plain, with milk or with ginger.",
      price: 250,
      tags: ["vegetarian"],
      options: OPTIONS.tea,
    },
    {
      slug: "fresh-lime-juice",
      image: unsplash("photo-1651993737174-6890c1daef5b"),
      name: t("Fresh lime juice", "දෙහි යුෂ", "எலுமிச்சை சாறு"),
      description: "Fresh lime, sweet or with a pinch of salt.",
      price: 350,
      tags: ["vegan"],
      options: OPTIONS.lime,
    },
    {
      slug: "woodapple-juice",
      name: t("Woodapple juice", "දිවුල් යුෂ", "விளாம்பழச் சாறு"),
      description: "Tangy woodapple blended with kithul jaggery.",
      price: 450,
      tags: ["vegan"],
    },
    {
      slug: "ginger-beer",
      name: t("House ginger beer", "ඉඟුරු බීම", "இஞ்சி பானம்"),
      description: "Fiery, freshly brewed and non-alcoholic.",
      price: 400,
      tags: ["vegan"],
    },
    {
      slug: "island-lager",
      image: unsplash("photo-1608270586620-248524c67de9"),
      name: t("Island lager", "ලාගර් බියර්", "லாகர் பீர்"),
      description: "Local lager, 625 ml. Not served on Poya days.",
      price: 1200,
      alcohol: true,
    },
    {
      slug: "coconut-arrack-sour",
      image: unsplash("photo-1609951651556-5334e2706168"),
      name: t("Coconut arrack sour", "පොල් අරක්කු සවර්", "தென்னை அரக் சவர்"),
      description:
        "Coconut arrack shaken with lime, kithul treacle and bitters. Not served on Poya days.",
      price: 1650,
      alcohol: true,
    },
  ],
};

export const menuItems: MenuItemRow[] = [];
export const itemOptions: ItemOptionRow[] = [];
export const itemOptionValues: ItemOptionValueRow[] = [];

for (const [categorySlug, specs] of Object.entries(MENU)) {
  specs.forEach((spec, index) => {
    const id = stableId("menu-item", spec.slug);
    menuItems.push({
      id,
      category_id: categoryId(categorySlug),
      slug: spec.slug,
      name_i18n: spec.name,
      description_i18n: { en: spec.description },
      base_price_cents: rs(spec.price),
      image_path: spec.image ?? null,
      dietary_tags: spec.tags ?? [],
      spice_selectable: spec.spicy ?? false,
      is_alcohol: spec.alcohol ?? false,
      is_signature: spec.signature ?? false,
      is_active: true,
      sort_order: index + 1,
    });

    (spec.options ?? []).forEach((option, optionIndex) => {
      const optionId = stableId("item-option", `${spec.slug}/${option.key}`);
      itemOptions.push({
        id: optionId,
        menu_item_id: id,
        name_i18n: option.name,
        selection: option.selection,
        is_required: option.required,
        max_select: option.maxSelect ?? null,
        sort_order: optionIndex + 1,
      });
      option.values.forEach((value, valueIndex) => {
        itemOptionValues.push({
          id: stableId("item-option-value", `${spec.slug}/${option.key}/${value.key}`),
          option_id: optionId,
          name_i18n: value.name,
          price_delta_cents: value.delta,
          is_default: value.isDefault ?? false,
          is_active: true,
          sort_order: valueIndex + 1,
        });
      });
    });
  });
}

const itemId = (slug: string) => stableId("menu-item", slug);

/** Per-branch differences, to show local pricing and sold-out states. */
export const branchMenuOverrides: BranchMenuOverrideRow[] = [
  {
    branch_id: branchId("nugegoda"),
    menu_item_id: itemId("chicken-kottu"),
    price_cents: rs(1550),
    is_available: true,
  },
  {
    branch_id: branchId("nugegoda"),
    menu_item_id: itemId("dolphin-kottu"),
    price_cents: null,
    is_available: false,
  },
  {
    branch_id: branchId("kandy"),
    menu_item_id: itemId("jaffna-crab-curry"),
    price_cents: null,
    is_available: false,
  },
  {
    branch_id: branchId("kandy"),
    menu_item_id: itemId("king-coconut"),
    price_cents: rs(300),
    is_available: true,
  },
  {
    branch_id: branchId("kandy"),
    menu_item_id: itemId("lamprais"),
    price_cents: rs(2350),
    is_available: true,
  },
];

// ---------------------------------------------------------------------------
// Promotions
// ---------------------------------------------------------------------------

const promotion = (row: Omit<PromotionRow, "id" | "image_path" | "is_active">) =>
  ({
    id: stableId("promotion", row.slug),
    image_path: null,
    is_active: true,
    ...row,
  }) satisfies PromotionRow;

export const promotions: PromotionRow[] = [
  promotion({
    slug: "kottu-tuesdays",
    title_i18n: t("Kottu Tuesdays", "කොත්තු අඟහරුවාදා", "கொத்து செவ்வாய்"),
    body_i18n: { en: "Every Tuesday from 6pm: any kottu and a king coconut for Rs. 1,800." },
    cta_label_i18n: t("Order kottu", "කොත්තු ඇණවුම් කරන්න", "கொத்து ஆர்டர் செய்யுங்கள்"),
    cta_href: "/menu#kottu",
    starts_on: null,
    ends_on: null,
    sort_order: 1,
  }),
  promotion({
    slug: "sunday-family-feast",
    title_i18n: t(
      "Sunday rice & curry for four",
      "ඉරිදා පවුලේ බත් පැකේජය",
      "ஞாயிறு குடும்ப விருந்து",
    ),
    body_i18n: {
      en: "Four rice & curry plates, a hopper basket and wattalappan for Rs. 6,950. Sundays only.",
    },
    cta_label_i18n: t("See rice & curry", "බත් සහ කරි බලන්න", "சோறும் கறியும் பார்க்க"),
    cta_href: "/menu#rice-and-curry",
    starts_on: null,
    ends_on: null,
    sort_order: 2,
  }),
  promotion({
    slug: "poya-vegetarian-lunch",
    title_i18n: t(
      "Poya day vegetarian lunch",
      "පොහොය දින නිර්මාංශ දිවා ආහාරය",
      "போயா தின சைவ மதிய உணவு",
    ),
    body_i18n: {
      en: "On every Poya day: seven vegetable curries, rice and a dessert for Rs. 1,450. Our bar stays closed.",
    },
    cta_label_i18n: t("View the menu", "මෙනුව බලන්න", "மெனுவைப் பார்க்க"),
    cta_href: "/menu#rice-and-curry",
    starts_on: null,
    ends_on: null,
    sort_order: 3,
  }),
  promotion({
    slug: "christmas-love-cake",
    title_i18n: t("Christmas love cake", "නත්තල් ලව් කේක්", "கிறிஸ்துமஸ் லவ் கேக்"),
    body_i18n: { en: "Pre-order a whole love cake or breudher for the festive table." },
    cta_label_i18n: t("Ask us", "අපෙන් අහන්න", "எங்களிடம் கேளுங்கள்"),
    cta_href: "/contact",
    starts_on: "2026-12-01",
    ends_on: "2026-12-26",
    sort_order: 4,
  }),
];

// ---------------------------------------------------------------------------
// Holidays (Poya dates from publicholidays.lk; 2027 is provisional)
// ---------------------------------------------------------------------------

const POYA_NAMES: Record<string, I18nText> = {
  duruthu: t("Duruthu", "දුරුතු", "துருது"),
  navam: t("Navam", "නවම්", "நவம்"),
  medin: t("Medin", "මැදින්", "மெதின்"),
  bak: t("Bak", "බක්", "பக்"),
  vesak: t("Vesak", "වෙසක්", "வெசாக்"),
  "adhi-poson": t("Adhi Poson", "අධි පොසොන්", "அதி பொசன்"),
  poson: t("Poson", "පොසොන්", "பொசன்"),
  esala: t("Esala", "ඇසළ", "எசல"),
  nikini: t("Nikini", "නිකිණි", "நிகினி"),
  binara: t("Binara", "බිනර", "பினர"),
  vap: t("Vap", "වප්", "வப்"),
  il: t("Il", "ඉල්", "இல்"),
  unduvap: t("Unduvap", "උඳුවප්", "உந்துவப்"),
};

const POYA_DAYS: [string, keyof typeof POYA_NAMES][] = [
  ["2026-01-03", "duruthu"],
  ["2026-02-01", "navam"],
  ["2026-03-02", "medin"],
  ["2026-04-01", "bak"],
  ["2026-05-01", "vesak"],
  ["2026-05-30", "adhi-poson"],
  ["2026-06-29", "poson"],
  ["2026-07-29", "esala"],
  ["2026-08-27", "nikini"],
  ["2026-09-26", "binara"],
  ["2026-10-25", "vap"],
  ["2026-11-24", "il"],
  ["2026-12-23", "unduvap"],
  ["2027-01-22", "duruthu"],
  ["2027-02-20", "navam"],
  ["2027-03-21", "medin"],
  ["2027-04-20", "bak"],
  ["2027-05-20", "vesak"],
  ["2027-06-18", "poson"],
  ["2027-07-18", "esala"],
  ["2027-08-16", "nikini"],
  ["2027-09-15", "binara"],
  ["2027-10-15", "vap"],
  ["2027-11-13", "il"],
  ["2027-12-13", "unduvap"],
];

export const holidays: HolidayRow[] = [
  ...POYA_DAYS.map(([date, key]) => {
    const name = POYA_NAMES[key]!;
    return {
      id: stableId("holiday", `poya/${date}`),
      date,
      kind: "poya" as const,
      name_i18n: {
        en: `${name.en} Full Moon Poya Day`,
        si: `${name.si} පුර පසළොස්වක පොහොය දිනය`,
        ta: `${name.ta} பூரணை போயா தினம்`,
      },
      is_alcohol_free: true,
    };
  }),
  {
    id: stableId("holiday", "festival/2026-12-25"),
    date: "2026-12-25",
    kind: "festival",
    name_i18n: t("Christmas Day", "නත්තල් දිනය", "கிறிஸ்துமஸ் தினம்"),
    is_alcohol_free: false,
  },
  {
    id: stableId("holiday", "festival/2027-04-13"),
    date: "2027-04-13",
    kind: "festival",
    name_i18n: t("Sinhala and Tamil New Year's Eve", "අලුත් අවුරුදු දා", "புத்தாண்டு முந்தைய நாள்"),
    is_alcohol_free: false,
  },
  {
    id: stableId("holiday", "festival/2027-04-14"),
    date: "2027-04-14",
    kind: "festival",
    name_i18n: t(
      "Sinhala and Tamil New Year",
      "සිංහල හා දෙමළ අලුත් අවුරුද්ද",
      "சிங்கள தமிழ் புத்தாண்டு",
    ),
    is_alcohol_free: false,
  },
];

// ---------------------------------------------------------------------------
// Reviews (fictional)
// ---------------------------------------------------------------------------

const review = (
  key: string,
  branchSlug: string | null,
  author_name: string,
  rating: number,
  body: string,
  created_at: string,
): ReviewRow => ({
  id: stableId("review", key),
  branch_id: branchSlug ? branchId(branchSlug) : null,
  author_name,
  rating,
  body,
  status: "approved",
  created_at,
});

export const reviews: ReviewRow[] = [
  review(
    "nadeesha",
    "colombo-07",
    "Nadeesha P.",
    5,
    "The dolphin kottu is ridiculous in the best way. Ordered for the office and it arrived hot, with extra gravy in a separate tub. Thoughtful.",
    "2026-09-12T13:20:00+05:30",
  ),
  review(
    "arjun",
    "nugegoda",
    "Arjun K.",
    5,
    "Egg hoppers that taste like my aachchi's. Crisp edges, runny yolk, proper lunu miris. We come every Friday now.",
    "2026-09-03T20:05:00+05:30",
  ),
  review(
    "fathima",
    "colombo-07",
    "Fathima R.",
    4,
    "Lovely to find a place that marks halal clearly. The chicken biriyani was fragrant and generous. Service was a little slow on a busy night.",
    "2026-08-28T19:40:00+05:30",
  ),
  review(
    "dilshan",
    "kandy",
    "Dilshan W.",
    5,
    "Booked a table for twelve after a perahera and they handled it beautifully. The wattalappan alone is worth the trip.",
    "2026-08-17T21:15:00+05:30",
  ),
  review(
    "priya",
    "nugegoda",
    "Priya S.",
    5,
    "Catered my mother's almsgiving for forty. Everything was on time, labelled, and the vegetable curries were outstanding.",
    "2026-07-30T11:00:00+05:30",
  ),
  review(
    "tom",
    "kandy",
    "Tom H.",
    4,
    "First proper Sri Lankan meal of our trip. Staff explained every dish and the 'Medium' spice was still an adventure for us.",
    "2026-07-21T14:30:00+05:30",
  ),
];
